unit UJogoDaVelhaTest;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Windows, Forms, Dialogs, Controls, Classes, SysUtils,
  Variants, Graphics, Messages, UJogoDaVelha;

type
  // Test methods for class TFormPrincipal

  JogoDaVelhaTest = class(TTestCase)
  strict private
    FJogoDaVelha : TJogoDaVelha;
  private
    procedure TestJogadorPodeJogar;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestTabuleiroLimpo;
    procedure TestJogoDaVelhaExists;
    procedure TestJogoDeveTerDoisJogadores;
    procedure TestJogadaPos1Valida;
    procedure TestJogador1PodeJogar;
    //procedure TestJogador2PodeJogar;
    //procedure TestValidaJogada();
  end;

implementation

procedure JogoDaVelhaTest.SetUp;
begin
  FJogoDaVelha := TJogoDaVelha.Create;
end;

procedure JogoDaVelhaTest.TearDown;
begin
  FreeAndNil(FJogoDaVelha);
end;


procedure JogoDaVelhaTest.TestJogadaPos1Valida;
begin
  CheckTrue(FJogoDaVelha.VerificaPosicao(1));
end;

procedure JogoDaVelhaTest.TestJogador1PodeJogar;
begin
  CheckTrue(FJogoDaVelha.VezJogador1);
end;


procedure JogoDaVelhaTest.TestJogadorPodeJogar;
begin

end;

procedure JogoDaVelhaTest.TestJogoDaVelhaExists;
begin
  CheckNotNull(FJogoDaVelha, 'Jogo da Velha não criado');
end;



procedure JogoDaVelhaTest.TestJogoDeveTerDoisJogadores;
begin
  CheckNotNull(FJogoDaVelha.Jogador1);
  CheckNotNull(FJogoDaVelha.Jogador2);

end;

procedure JogoDaVelhaTest.TestTabuleiroLimpo;
begin
   CheckTrue( FJogoDaVelha.isvazio);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(JogoDaVelhaTest.Suite);
end.

